
# Presidio version information: https://github.com/microsoft/presidio/releases

# analyzer service configuration
analyzer:
  replicas: 1
  imageRepository: mcr.microsoft.com/presidio-analyzer
  imagePullPolicy: Always
  # Presidio version information: https://github.com/microsoft/presidio/releases
  imageTag: latest
  resources:
    limits:
      cpu: 512m
      memory: 1024Mi
    requests:
      cpu: 256m
      memory: 1024Mi

# anonymizer service configuration
anonymizer:
  replicas: 1
  imageRepository: mcr.microsoft.com/presidio-anonymizer
  imagePullPolicy: Always
  # Presidio version information: https://github.com/microsoft/presidio/releases
  imageTag: latest
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 512Mi
