apiVersion: apps/v1
kind: Deployment
metadata:
  name: presidio-analyzer
spec:
  replicas: {{ .Values.analyzer.replicas | default 1 }}
  selector:
    matchLabels:
      app: presidio-analyzer
  template:
    metadata:
      labels:
        app: presidio-analyzer
    spec:
      containers:
      - image: '{{ .Values.analyzer.imageRepository | default "mcr.microsoft.com/presidio-analyzer" }}:{{ .Values.analyzer.imageTag | default "latest" }}'
        name: presidio-analyzer
        imagePullPolicy: {{ .Values.analyzer.imagePullPolicy | default "Always" }}
        resources:
          {{- toYaml .Values.analyzer.resources | nindent 10 }}
        ports:
        - containerPort: 3000
          name: api
      {{- with .Values.analyzer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.analyzer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.analyzer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presidio-anonymizer
spec:
  replicas: {{ .Values.anonymizer.replicas | default 1 }}
  selector:
    matchLabels:
      app: presidio-anonymizer
  template:
    metadata:
      labels:
        app: presidio-anonymizer
    spec:
      containers:
      - image: '{{ .Values.anonymizer.imageRepository | default "mcr.microsoft.com/presidio-anonymizer" }}:{{ .Values.anonymizer.imageTag | default "latest" }}'
        name: presidio-anonymizer
        imagePullPolicy: {{ .Values.anonymizer.imagePullPolicy | default "Always" }}
        resources:
          {{- toYaml .Values.anonymizer.resources | nindent 10 }}
        ports:
        - containerPort: 3000
          name: api
      {{- with .Values.anonymizer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anonymizer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anonymizer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: presidio-analyzer
spec:
  selector:
    app: presidio-analyzer
  ports:
    - port: 3000
      name: api
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: presidio-anonymizer
spec:
  selector:
    app: presidio-anonymizer
  ports:
    - port: 3000
      name: api
      protocol: TCP
      targetPort: 3000
